Update people
lr-vu/siteOLD pull request #1
Opened 2022-09-20 17:55 UTC by tae898

2022-09-20 23:31 UTC, miselico requested changes
Can you revert the front matter (the part between the ---'s). And then also add the closing tags for the links?

2022-09-20 23:31 UTC, miselico commented on people/index.md
> +______________________________________________________________________
We have to keep the markdown block as is. The block between --- contains information that is parsed by jekyll to indicate that this must be rendered as a page

2022-09-20 23:31 UTC, miselico commented on people/index.md
> +    <figure><a href="http://sauter.at/"><img src="{{ site.baseurl }}images/members/Andreas.png" class="people_gallery__img" alt="Image 1">
For all links, you are missing the closing of the tag. So, before the img, you open it with <a ...> after the caption, you must close it with </a>

2022-09-21 13:31 UTC, miselico approved these changes
LGTM

2022-09-21 13:31 UTC, merged

2022-09-21 13:32 UTC, tae898 commented
![image](https://user-images.githubusercontent.com/10544311/191517557-9e4a34f4-0540-4f6a-b56f-fdbcdef6f97e.png)